[package]
name = "rokoblox/argon-codebase"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
cmdr = "evaera/cmdr@1.12.0"
Trove = "sleitnick/trove@1.5.0"
TypedRemote = "sleitnick/typed-remote@0.2.0"
TaskQueue = "sleitnick/task-queue@1.0.0"
Net = "sleitnick/net@0.2.0"
lemonsignal = "data-oriented-house/lemonsignal@1.11.0"
